server:
  host: 0.0.0.0
  port: 8124
commands:
  volume_up: JgBYAAABJpURFBEUETkRFBEUERQRFBEUEjgROREUETkRORE5EToQOREUETkRFBEUERUQFRAVEBUQOhAVEDoQOhA6EDoQOhA6EAAFKQABJUwTAAxdAAElTBMADQU=
  volume_down: JgBQAAABJpURFBEUETkRFBEUERQRFBEUETkROREUETkRORE5ETkRORE5ETkRFRAVEBUSEhIUEBUQFRAVEDoQOhA6EDoQOhA6EAAFKQABJksRAA0FAAAAAAAAAAA=


